spring:
  datasource:
      url: jdbc:postgresql://postgres:5432/executor
      username: executor_user
      password: executor_pass
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate